### PR TITLE
lab3 submitted

### PR DESCRIPTION
**Pull request by deefuture**
https://deefuture.github.io/CSCN8010-lab-submissions/8900611/lab3.html

### CODE REVIEW

**Review by RanFeldesh — CHANGES_REQUESTED** [review]
5/6 points.
looking at the html,
why have you chosen a log-log plot for the last figure?
why haven't you addressed the issue with the error message?
Your submission includes two additional files, that seem redundant, can you please remove them from this pull request (PR)? this is required for merging and grading:

image

**Comment by deefuture** [comment]
Hi sir, am trying my best here to do that but I couldn’t may be tomorrow
sir you can be of help to me and am waiting for one of my colleagues to
come explain how I will go about that. Thanks in advance

**Comment by deefuture** [comment]
Hello sir, you can check back now sir, I have try to remove it, thank you
sir

**Review by RanFeldesh — APPROVED** [review]
Thanks, looks good !

**Pull request merged**
