### PR TITLE
Waseem Iqbal Shaikh - 8902834 - Practical lab 2

### PR DESCRIPTION
**Pull request by WaseemShaikh16**
https://waseemshaikh16.github.io/CSCN8010-lab-submissions/8902834/lab2.html

### CODE REVIEW

**Review by RanFeldesh — CHANGES_REQUESTED** [review]
Hi Waseem,

This is a great notebook !

I appreciate the usage of all 3 packages, and the links that you provided to the sources. 

Before this can be graded and merged, I see that you modified the `practical_labs/lab1.ipynb` file. Can you please undo these changes? This is not a file that is your folder, but is one I wrote for all students as a reference. Thanks.

Great submission overall.

**Comment by WaseemShaikh16** [comment]
@RanFeldesh professor, I have made required changes. please check it.

**Review by RanFeldesh — APPROVED** [review]
Thanks for making the fix Waseem, 
Great job
6/6 points

**Comment by WaseemShaikh16** [comment]
Dear Professor,

Thank you so much @Ran ***@***.***> professor! Have an amazing weekend.

Regards,
Waseem Iqbal Shaikh
________________________________

**Pull request merged**
