### PR TITLE
lab3 submitted & 4, 5 and 6 submitted

### PR DESCRIPTION
**Pull request by Amandeepkaur-conestoga19**
https://amandeepkaur-conestoga19.github.io/CSCN8010-lab-submissions/8896062/lab3.html
https://amandeepkaur-conestoga19.github.io/CSCN8010-lab-submissions/8896062/lab4.html
https://amandeepkaur-conestoga19.github.io/CSCN8010-lab-submissions/8896062/lab5.html

### CODE REVIEW

**Review by RanFeldesh — APPROVED** [review]
Good analysis, 6/6 points.
For the heatmap, next time it is good to print the values for each entry.

**Review by RanFeldesh — CHANGES_REQUESTED** [review]
Please remove these changes from the PR (pull request), this is required for merging and grading:
image

**Comment by RanFeldesh** [comment]
Hi @Amandeepkaur-conestoga19 ,

This is a kind reminder to fix the issue with the files in this PR, such that this lab can be graded and merged. Thanks. See my comment above (on Github)

**Comment by RanFeldesh** [comment]
Hi @Amandeepkaur-conestoga19 ,

Thank you for deleting most of the files. 
There is a last one to delete, in the subfolder `12345678`. 

Then I could grade and merge. 

Thanks :)

**Comment by Amandeepkaur-conestoga19** [comment]
I have done the required changes. Please ignore the read me files in my folder.

**Comment by Amandeepkaur-conestoga19** [comment]
https://amandeepkaur-conestoga19.github.io/CSCN8010-lab-submissions/8896062/lab6.html

**Review by RanFeldesh — APPROVED** [review]
Lab 4: 5.5/6 points. Deeper dive about the graphs would have been great, like we did in class, but overall a great submission.

Lab 5: 5/6 points, I think that there is a bug with degrees 0 and 1 being exactly the same in their evaluation metrics. STD should have been calculated per model to allow a better comparison. But again, good submission !

Lab 6: 5/6 . Looking into why the fit is almost perfect would have been good, as a perfect fit is an indication of a potential bug (none in this case), **Note that a large part of this submission appear in a different notebook of another student. Please make sure that this won't happen again.**

**Pull request merged**
