### PR TITLE
Mohammed Abuzar Younus 8903244

### PR DESCRIPTION
**Pull request by M-younus88**
https://m-younus88.github.io/CSCN8010-lab-submissions/8903244/abuzar_lab2.html

### CODE REVIEW

**Review by RanFeldesh — CHANGES_REQUESTED** [review]
Minimal work, but looks good, I'm looking forward to see what you will create next in the following labs and going forward.

**I see that you deleted the README file of the repository. You would need to revert this change for this PR to be merged, and for you to get the grade for it. **

**Comment by M-younus88** [comment]
sir i can see my readme file over there

**Comment by RanFeldesh** [comment]
You deleted the one that I created in the root folder of this repository. 
I am not speaking about your README, but the one I created. Please fix :) thanks

**Comment by M-younus88** [comment]
Hello sir can u check once I have updated

**Review by RanFeldesh — APPROVED** [review]
Thanks for the quick and good fix.
Looks good !

6/6 points

**Pull request merged**
