### PR TITLE
Rohit Kumar pull request

### PR DESCRIPTION
**Pull request by Rohitsachdeva**
Hello sir, 

Please merge my request, if there is any issue, please let me know.

have a nice day
Rohit

### CODE REVIEW

**Comment by RanFeldesh** [comment]
I see that you added an HTML. can you add the link to its live URL (from your forked repository) to the PR description ? This will yield the full 6 points for this lab.

**Comment by Rohitsachdeva** [comment]
Hello sir,

This is the link of the html 

https://github.com/Rohitsachdeva/CSCN8010-lab-submissions/blob/main/docs/8895806/RohitKumar.html

I am not able to view it as preview page, after downloading this page locally then I am able to view it.


Thanks
Rohit Kumar

**Comment by RanFeldesh** [comment]
The link to the live URL should be:
https://rohitsachdeva.github.io/CSCN8010-lab-submissions/RohitKumar.html

Have you enabled github pages on the settings? see the instructions with the screen capture:
https://github.com/Conestoga-AAIML-2023-Spring/CSCN8010/tree/main/class_notebooks/github_pages

Right now you have 5/6 points, if you can get it work before the deadline, you can get 6/6, and have this important tool in your toolbox.

**Comment by Rohitsachdeva** [comment]
https://rohitsachdeva.github.io/CSCN8010-lab-submissions/8895806/RohitKumar.html

**Comment by RanFeldesh** [comment]
Awesome ! thank you , that worked. Indeed, your student id is part of the url, which I was missing in the url I suggested above. 

Can you please delete the **second** HTML that you created earlier today locally, and push this change? such that it won't be merged, as it is not needed.


Great job !

**Comment by Rohitsachdeva** [comment]
I have deleted.

**Review by RanFeldesh — APPROVED** [review]
LGTM ! 
Great job Rohit !
Thanks for the clear and effective communication as well.

**Pull request merged**
