### PR TITLE
Lab 3 Rohit Kumar 8895806

### PR DESCRIPTION
**Pull request by Rohitsachdeva**
https://rohitsachdeva.github.io/CSCN8010-lab-submissions/8895806/RohitKumarLab3.html

### CODE REVIEW

**Comment by Rohitsachdeva** [comment]
the correct url is :
https://rohitsachdeva.github.io/CSCN8010-lab-submissions/8895806/RohitKumarLab3.html

**Comment by RanFeldesh** [comment]
Hi Rohit, Just wonder, why did you close the PR (Pull Request)?

**Comment by RanFeldesh** [comment]
If this was done by mistake, you can just re-open it  here on Github

**Comment by Rohitsachdeva** [comment]
There were many mistakes.


Sorry for inconvenience. I want to up new one.

**Comment by Rohitsachdeva** [comment]
https://rohitsachdeva.github.io/CSCN8010-lab-submissions/8895806/RohitKumarLab3.html

**Review by RanFeldesh — APPROVED** [review]
6/6 points.
But I'd love a bit more text around your code, interpreting the results it provides.

**Pull request merged**
