### PR TITLE
Completed Lab 2

### PR DESCRIPTION
**Pull request by officialhariprasath**
https://officialhariprasath.github.io/CSCN8010-lab-submissions/8901541/lab2.html

### CODE REVIEW

**Review by RanFeldesh — CHANGES_REQUESTED** [review]
Hi Hari,

* Your notebook is good. 

As part of this PR (Pull Request) you have made some changes that can impact all students if we were t o merge them:
* You deleted the file `8896062/README.md` by Amandeep. I assume that this was done by mistake? If there is no reason to delete it, can you please undo this change?
* I see that you copied the requirements.txt` file to this repository. This is not required, as we can use the same environment as the CSCN8010 repository. So can you please delete this file here?

Once you fix these two issues locally, you can commit and push them. This will update this PR automatically. 

Then I could approve this PR, merge it, and update your grade. Assuming it is done in a timely manner, your grade will be 5/6, pretty good ! 


Overall good job, and I understand that part of the learnings are related to github, git, and python environments. This is good to learn now, during your studies, such that when you get to interviews and more importantly actual work - you will be able to hit the ground running and be a high performer.

**Comment by RanFeldesh** [comment]
One more small thing, Have you enabled Github Pages? before the link to the HTML that you shared, which seems correct, is showing a `404 - page doesn't exist`.

**Comment by RanFeldesh** [comment]
Hi Harry, I hope that I find you well.
If you would like your grade to be 5/6 for this assignment, please make the updates requested above by end of Wednesday, May 31st. You've done a great job with this lab, and it would be great to get the grade for it. If you need assistance, I'd first see if one of your classmates can help you. Otherwise, I can guide you after Wednesday's class. Best, and I look forward to see what you'll create next.

**Comment by officialhariprasath** [comment]
Hi Professor,

I have made changes as required.
Can you please check them ?

Thanks,
Hari Prasath.

**Review by RanFeldesh — APPROVED** [review]
Hi Harry, 
Thank you for making this changes. This looks great. 
I look forward to see what you will create next.

5/6 points for this lab.

**Pull request merged**
